import json
import time
from pathlib import Path
from model import GPT
from model_v2 import GPT2
from model_v3 import GPT3
from config import GPTConfig
import torch
import tiktoken

CHECKPOINT="checkpoints_mHC/best.pt"
VOCAB_PATH="data/tinystories/vocab.json"
PROMPT="Once upon a time, there was a brave little mouse. He wanted to cross the big river but he was scared. He tried once and failed. He tried again and failed. But on the third try,"
MAX_TOKENS=350
TOP_K=40
NUM_STORIES=3
TEMPERATURE=0.85
USE_KV_CACHE=True
VERSION=3
EOS_ID = 9999  # Your newly trained EOS token ID

def load_vocab(path):
    with open(path, mode="r", encoding="utf-8") as f:
        token_to_id = json.load(f)
    id_to_token = {v: k for k, v in token_to_id.items()}
    return token_to_id, id_to_token

def encode(text, token_to_id):
    enc = tiktoken.get_encoding("gpt2")
    gpt2_ids = enc.encode(text)
    
    ids = []
    for gpt2_id in gpt2_ids:
        key = str(gpt2_id)  
        if key in token_to_id:
            ids.append(token_to_id[key])
        else:
            print(f"[Warning] GPT-2 token {gpt2_id} not in vocab, skipping")
    return ids

def decode(ids, id_to_token):
    enc = tiktoken.get_encoding("gpt2")
    # Filter out the EOS token during final string decoding so it doesn't cause errors
    gpt2_ids = [int(id_to_token[i]) for i in ids if i in id_to_token and i != EOS_ID]
    return enc.decode(gpt2_ids)

def load_model(checkpoint_path):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    checkpoint = torch.load(checkpoint_path, map_location=device)
    model_config = GPTConfig(**checkpoint["model_config"])

    if VERSION == 2:
        print("[NanoTales] Detected v2.0 — SwiGLU + Muon config")
        model = GPT2(model_config).to(device)
    elif VERSION == 3:
        print("[NanoTales] Detected v3.0 — mHC + Muon config")
        model = GPT3(config=model_config).to(device)
    else:
        print("[NanoTales] Detected v1.0 — standard config")
        model = GPT(model_config).to(device)

    state_dict = checkpoint["model"]
    unwanted_prefix = '_orig_mod.'
    for k, v in list(state_dict.items()):
        if k.startswith(unwanted_prefix):
            state_dict[k[len(unwanted_prefix):]] = state_dict.pop(k)
            
    model.load_state_dict(state_dict)
    model.eval()

    print(f"[NanoTales] Loaded checkpoint from step {checkpoint['step']}")
    print(f"[NanoTales] Val loss at checkpoint: {checkpoint['loss']:.4f}")
    print(f"[NanoTales] Running on: {device}")
    
    return model, device

def generate_story(model, device, token_to_id, id_to_token, prompt, max_tokens, temperature, top_k, use_kv_cache):
    prompt_ids = encode(prompt, token_to_id)
    idx = torch.tensor([prompt_ids], dtype=torch.long, device=device)

    with torch.no_grad():
        # Pass EOS_ID to the model's generate method
        output = model.generate(
            idx, 
            max_new_tokens=max_tokens, 
            temperature=temperature, 
            top_k=top_k, 
            use_kv_cache=use_kv_cache,
            eos_id=EOS_ID  # The model will now stop internally when it hits 9999
        )

    generated_ids = output[0].tolist()
    
    # Check if/where EOS appeared to slice the list before decoding
    if EOS_ID in generated_ids:
        eos_index = generated_ids.index(EOS_ID)
        generated_ids = generated_ids[:eos_index]

    return decode(generated_ids, id_to_token).strip()

def main():
    print(f"[NanoTales] Loading vocab from {VOCAB_PATH}...")
    token_to_id, id_to_token = load_vocab(VOCAB_PATH)
    print(f"[NanoTales] Vocab size: {len(token_to_id):,} tokens")

    model, device = load_model(CHECKPOINT)
    
    print(f"\n[NanoTales] Prompt: '{PROMPT}'")
    print(f"[NanoTales] Generating {NUM_STORIES} stories...\n")
    print("=" * 60)

    for i in range(NUM_STORIES):
        t1 = time.time()
        story = generate_story(
            model, device,
            token_to_id, id_to_token,
            PROMPT, MAX_TOKENS, TEMPERATURE, TOP_K,
            use_kv_cache=USE_KV_CACHE
        )
        t2 = time.time()
        elapsed = t2 - t1
        
        # Calculate tokens generated by counting length of the output IDs if needed, 
        # but for simplicity we'll show time taken.
        print(f"\nStory {i+1}:\n")
        print(story)
        print(f"\nTime taken: {elapsed:.2f}s")
        print("\n" + "=" * 60)

if __name__ == "__main__":
    main()